// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using uBid.Models;

namespace uBid.Migrations
{
    [DbContext(typeof(uBidContext))]
    [Migration("20181121010211_ThirdCreate")]
    partial class ThirdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("uBid.Models.ItemModel", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("category");

                    b.Property<DateTime>("endTime");

                    b.Property<double>("highestBid");

                    b.Property<string>("longDesc");

                    b.Property<string>("modelNum");

                    b.Property<string>("name");

                    b.Property<double>("reservePrice");

                    b.Property<string>("serialNum");

                    b.Property<string>("shortDesc");

                    b.Property<DateTime>("startTime");

                    b.HasKey("itemID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("uBid.Models.UserModel", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<string>("billAddress");

                    b.Property<string>("billZip");

                    b.Property<long>("creditCard");

                    b.Property<string>("emails");

                    b.Property<string>("passWord");

                    b.Property<string>("userName");

                    b.Property<string>("zip");

                    b.HasKey("userID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
